# Project information
site_name: 'Kadena Documentation'

site_description: 'Kadena Dcocumentation'
site_author: 'Kadena'
# site_url: 'pactlang.org'

# Repository
repo_name: 'kadena-io/kadena-docs'
repo_url: 'https://github.com/kadena-io/kadena-docs/'

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 Kadena'

    # Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  feature:
    tabs: true
  font:
    text: 'Helvetica'
    code: 'Helvetica'
  favicon: 'assets/images/logo.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kadena-io'
    - type: 'twitter'
      link: 'https://twitter.com/kadena_io'

## google_analytics:
  ## - 'UA-127512784-3'
  ## - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true

nav:
- FAQs: 
  - './FAQs.md'

- Glossary:
  - './Glossary.md'

#- Public Chain:
#  - 'I want to run my own node': './Chainweb/chainweb-node-actions.md'
#  - 'I want to mine': './Chainweb/chainweb-miner-actions.md'
#  - 'I want to create keys / transfer coins': './Chainweb/Keys-and-Wallets.md'
#  - 'Other': './Chainweb/Other.md'

# - Pact:
#   - 'Pact': https://pactlang.org/

# - Chainweaver:
#   - 'Support Page': https://www.kadena.io/chainweaver