# Project information
site_name: 'Kadena Documentation'

site_description: 'Chainweaver Support'
site_author: 'Kadena'
# site_url: 'pactlang.org'

# Repository
repo_name: 'kadena-io/chainweaver-support'
repo_url: 'https://github.com/kadena-io/chainweaver-support/'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Kadena'

    # Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  feature:
    tabs: true
  font:
    text: 'Helvetica'
    code: 'Helvetica'
  favicon: 'assets/images/logo.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kadena-io'
    - type: 'twitter'
      link: 'https://twitter.com/kadena_io'

## google_analytics:
  ## - 'UA-127512784-3'
  ## - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true

nav:
- Chainweb:
  - 'Networks': './Chainweb/chainweb-networks.md'
  - 'Node Actions': './Chainweb/chainweb-node-actions.md'
  - 'Block Explorer': https://explorer.chainweb.com/mainnet
  - 'Miner Actions': './Chainweb/chainweb-miner-actions.md'
 # - 'Kadena Community':

- Pact:
  - 'Main Page': https://pactlang.org/

- Chainweaver:
  - 'Test file': ./Chainweaver/chainweaver-first-file.md
  - 'Second File': './Chainweaver/chainweaver-second-file.md'

 # - Kuro:
 # - 'Coming Soon'
 # - 'My File'