# Project information
site_name: 'Kadena Docs'
site_description: 'Kadena Documentation'
site_author: 'Kadena'
site_url: ''

# Repository
repo_name: 'kadena-io/kadena-docs'
repo_url: 'https://github.com/kadena-io/kadena-docs/'

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 Kadena'

    # Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  feature:
    tabs: false
  font:
    text: 'Helvetica'
    code: 'Helvetica'
  favicon: 'assets/chainweaver-support-favicon-512.png'

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/kadena-io'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/kadena_io'

## google_analytics:
  ## - 'UA-127512784-3'
  ## - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true

nav:
- What is Kadena?: what-is-kadena.md
- What is KDA?: what-is-kda.md
- Kadena FAQ: FAQs.md
- Public Chain Resources: Public-Chain-Docs.md
- Private Chain Resources: Private-Chain-Docs.md
